version: build-{build}
max_jobs: 1
image: Visual Studio 2017
clone_folder: C:\prj\test-appveyor
platform:
    - x86
#    - x64
build_script:
- cmd: >-
    SET

    SET PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%path%

    cd C:\prj

    c:\Python36-x64\python --version

    c:\Python36-x64\python -m pip list

    c:\Python36-x64\python -m virtualenv venv

    venv\Scripts\activate

    python -m pip install "pip<19.0"

    pip list

    pip install pyinstaller

    pip install cython

    pip install numpy

    cd C:\prj\test-appveyor

    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    python setup.py build_ext --inplace

    md ..\compile_pyd

    xcopy .\*.pyd ..\compile_pyd /s /y

#xcopy .\*.pyd compile_pyd /exclude:exclude.txt /s

after_build:
    7z a .\compile_pyd-b%APPVEYOR_BUILD_NUMBER%.zip ..\compile_pyd\*

    dir

    chdir

artifacts:
- path: compile_pyd-b%APPVEYOR_BUILD_NUMBER%.zip

deploy:
  artifact: compile_pyd-b%APPVEYOR_BUILD_NUMBER%.zip
  prerelease: true
  description: 'Test Release'
  provider: GitHub
  auth_token:
    secure: gb7NBwSinsyPgvJSkCDgUNjxAzqCqRbPEN3b0oX1XF92PAxuy2Opyk+Rbvw660R3
  on:
    # branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
