version: build-{build}
max_jobs: 1
image: Visual Studio 2017
clone_folder: C:\prj\test-appveyor

build_script:
- ps: cd C:\prj\test-appveyor
- ps: .\appveyor_windows_steps.ps1

#after_build:
#    7z a .\compile_pyd-b%APPVEYOR_BUILD_NUMBER%.zip ..\compile_pyd\*
#
#    dir
#
#    chdir

artifacts:
- path: compiled_pyd-b%APPVEYOR_BUILD_NUMBER%.zip

deploy:
  artifact: compiled_pyd-b%APPVEYOR_BUILD_NUMBER%.zip
  prerelease: true
  description: 'Test Release'
  provider: GitHub
  auth_token:
    secure: gb7NBwSinsyPgvJSkCDgUNjxAzqCqRbPEN3b0oX1XF92PAxuy2Opyk+Rbvw660R3
  on:
    # branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
