version: build-{build}
max_jobs: 1
image: Visual Studio 2015
clone_folder: C:\prj\test-appveyor

build_script:
- ps: cd C:\prj\test-appveyor
- ps: .\appveyor_windows_steps.ps1

after_build:
    7z a .\compiled_pyd-b%APPVEYOR_BUILD_NUMBER%.zip ..\compiled_pyd\*

artifacts:
- path: compiled_pyd-b%APPVEYOR_BUILD_NUMBER%.zip

deploy:
  artifact: compiled_pyd-b%APPVEYOR_BUILD_NUMBER%.zip
  prerelease: true
  description: 'Test Release'
  provider: GitHub
  auth_token: 358520c8aa573ded4e37b31073493828bdc4d5ba
#    secure:
#  on:
#     branch: master                 # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only
